### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by akrzemi1** [atomgalaxy/wg21-abort-only-contract-support#1]
- [x] Discuss a call through a pointer
- [x] Describe caller perspective of values referred in postconditions
- [x] Describe lookup in virtual functions
- [x] Describe what you can and cannot do with the MVP.
  - [x] Address Bjarne's question: how to use the Standard Library if I cannot afford the cost of checking
  - [x] Address the needs of zero-overhead users.
- [x] Address assumptions: they are indirectly supported.
- [ ] Add note on implementability: you can always just evaluate pre and post inside function body and provide two versions of the Standard Library
- [x] Describe the vision of for The Standard Library: even in the future we will allow but not require the usage of contract annotations.
- [x] Show migration path to future extensions. (A question from Tony VE.) Additional behavior will be an opt-in, either through annotations or compiler switches.
- [x] Wording: add example illustrating 9.12.4.3p10.
- [x] Describe the difference between mathematical predicates and C++ predicates, and the wording difficulties that arise from this difference.
- [x] Discuss postconditions for types without value semantics (Ville's question).
- [x] Explain that contracts are a different language, although similar to C++ expressions
- [x] Highlight: if you add postcondition, the function definition may become ill-formed.
- [x] Describe `const_cast`
- [x] Describe SG22 concerns
- [x] Mention P2049 (reference implementation)
